#!/bin/bash
#https://www.linkedin.com/pulse/unlocking-potential-comprehensive-guide-using-media-controller-kumar-nplsc
#https://wiki.geekworm.com/CSI_Manual_on_Pi_5

#✔ 1280x720p60
#✔ 1280x1024
#✔ 1920x1080i60
#✔ 1920x1080i50
#✔ 1920x1080p60
#✔ 1920x1080p50
#✔ 1600x1200p5
#✔ 1920x1080i120

./hdmi3.sh $* | tee hdmi.log

