#!/bin/bash
#
BASE=$(dirname  $0)
echo $BASE
sleep 3

if [ "$1" == "" ]; then
	$BASE/hdmi3.sh --frames 2 --encode RGB888 | tee /home/dwade/hdmi3.log
else
	$BASE/hdmi3.sh $* | tee /home/dwade/hdmi3.log
fi
chown dwade:dwade /home/dwade/hdmi3.log
